### ISSUE TITLE
Using GMSMarker instead of GClusterItem

### ISSUE THREAD

**Issue by ghost** [eyaldar/google-maps-ios-utils-swift#2]
Is it possible to use GMSMarker instead of GClusterItem?
Because in my app I'm changing icons, zIndex and a lot of other GMSMarker properties and GClusterItem only have the location.

**Comment by eyaldar** [comment]
GClusterItem is actually just the underlying data object. in order to control view changes implement a custom GClusterRenderer and change whatever you want there.
(You can theoretically make GMSMarker extend GClusterItem but I wouldn't recommend it).

Also note that google recently added clustering capabilities to their original utils library which I haven't found the time check out yet but I would expect it to perform better, check it out if your not in a hurry:
https://github.com/googlemaps/google-maps-ios-utils
